export const data = [
    {
      id: 1,
      name: 'Wilmette',
      dob: '1-10-1998',
      email: 'wmaasz0@jalbum.net',
      role: 'Software Engineer',
    },
    {
      id: 2,
      name: 'John Doe',
      dob: '5-15-1985',
      email: 'john.doe@example.com',
      role: 'Data Scientist',
    },
    {
      id: 3,
      name: 'Jane Smith',
      dob: '8-20-1990',
      email: 'jane.smith@example.com',
      role: 'Product Manager',
    },
    {
      id: 4,
      name: 'Alice Johnson',
      dob: '4-5-1982',
      email: 'alice.johnson@example.com',
      role: 'UX Designer',
    },
    {
      id: 5,
      name: 'Bob Williams',
      dob: '12-30-1975',
      email: 'bob.williams@example.com',
      role: 'Marketing Specialist',
    },
    {
      id: 6,
      name: 'Eva Brown',
      dob: '9-18-1988',
      email: 'eva.brown@example.com',
      role: 'Financial Analyst',
    },
    {
      id: 7,
      name: 'David Miller',
      dob: '7-12-1995',
      email: 'david.miller@example.com',
      role: 'HR Manager',
    },
    {
      id: 8,
      name: 'Grace Davis',
      dob: '2-8-1980',
      email: 'grace.davis@example.com',
      role: 'Software Developer',
    },
    {
      id: 9,
      name: 'Michael Taylor',
      dob: '11-3-1993',
      email: 'michael.taylor@example.com',
      role: 'Network Administrator',
    },
    {
      id: 10,
      name: 'Olivia White',
      dob: '6-22-1987',
      email: 'olivia.white@example.com',
      role: 'Sales Manager',
    },
    {
      id: 11,
      name: 'Ryan Smith',
      dob: '3-15-2002',
      email: 'ryan.smith@example.com',
      role: 'Graphic Designer',
    },
    {
      id: 12,
      name: 'Sophia Brown',
      dob: '10-8-1991',
      email: 'sophia.brown@example.com',
      role: 'Content Writer',
    },
    {
      id: 13,
      name: 'Daniel Wilson',
      dob: '7-19-1984',
      email: 'daniel.wilson@example.com',
      role: 'Project Manager',
    },
    {
      id: 14,
      name: 'Emma Johnson',
      dob: '4-26-1978',
      email: 'emma.johnson@example.com',
      role: 'QA Engineer',
    },
    {
      id: 15,
      name: 'William Davis',
      dob: '9-5-1996',
      email: 'william.davis@example.com',
      role: 'Business Analyst',
    },
  ];
  